version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dev_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    build: .
    container_name: backend_dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://devuser:devpassword@postgres:5432/dev_db"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data_dev:
    driver: local
