services:
  api:
    build: .
    container_name: backend_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app # Live reload
      - /app/node_modules # Prevents overwriting node_modues

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
