services:
  postgres:
    image: postgres:15
    container_name: postgres_test
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_test:
    driver: local
